on: [pull_request]

permissions:
  actions: write

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        ghc:
          - '9.12'
          - '9.10'
          - '9.8'
          - '9.6'
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Cabal cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cabal update
      run: cabal update
    - name: Build using cabal
      run: cabal build all
    # TODO figure out how to run integration tests
    # - name: Test
    #   run: cabal test all
    - name: Cancel workflow on failure
      if: failure()
      continue-on-error: true
      run: gh run cancel ${{ github.run_id }}
      env:
        GH_TOKEN: ${{ github.token }}
